name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create .env File from GitHub Secrets
        run: echo "${{ secrets.ALL_ENV }}" > .env

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker info  # Check if login was successful

      - name: Build Docker Image
        run: docker build --build-arg ALL_ENV="${{ secrets.ALL_ENV }}" -t ${{ secrets.DOCKER_USERNAME }}/authorslens:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/authorslens:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to Production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deploying docker app to EC2 instance..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/authorslens:latest && \
            sudo docker stop authorslens || true && \
            sudo docker rm authorslens || true && \
            echo "${{ secrets.ALL_ENV }}" > .env && \
            sudo docker run -d --name authorslens --env-file .env -p 80:80 ${{ secrets.DOCKER_USERNAME }}/authorslens:latest && \
            echo "Deployment completed successfully!"
